name: SomtumMC
version: '${project.version}'
main: fur.unityg.somtummc.SomtumMC
api-version: '1.20'
depend: [spark, LuckPerms, NoteBlockAPI]
authors: [FurryGang, Phapoom Saksri]
description: "Fun Fact: I don't know how to code in java."
website: https://somtum.fun
commands:
  rules:
    description: It is /rules, Like who read rules smh.
    aliases:
      - rule
      - tos
      - terms
    usage: /<command>
  gamemode:
    description: It is /gamemode
    aliases:
      - gm
      - gammode
      - givemecreativenerd
    usage: /<command> [survival | creative | adventure | spectator]
    permission: somtum.gamemode
  sethome:
    description: It is /sethome
    aliases:
      - sethouse
      - seth
      - savehome
    usage: /<command>
  home:
    description: It is /home
    aliases:
      - house
      - hom
      - mybed
    usage: /<command>
  delhome:
    description: It is /delhome
    aliases:
      - deletehome
      - deletehouse
      - byebyehome
    usage: /<command>
  togglejoinmusic:
    description: It is /togglejoinmusic
    aliases:
      - tjm
      - togglemusic
      - togglejoin
    usage: /<command>
  stopsong:
    description: It is /stopsong
    aliases:
      - ihatemusic
      - stopmusic
      - musicstop
      - ms
      - endmusic
    usage: /<command>
  playmusic:
    description: It is /playmusic
    aliases:
      - pm
      - songplay
      - playsong
      - ps
      - sp
      - music
    usage: /<command>