name: SomtumMC
version: '${project.version}'
main: fur.unityg.somtummc.SomtumMC
api-version: '1.20'
depend: [spark, LuckPerms]
authors: [UnityG, Phapoom Saksri]
description: "Can’t stop playing AMONG USSSSSSSSSS,
                              I love Among USSSSSSSS - Phapoom Saksri... 2024-5-17"
website: https://somtum.fun
commands:
  rules:
    description: Rules Command.
    aliases:
      - rule
      - rules
      - imnotshutcre
    usage: /<command>
  gamemode:
    description: hai :3 its a gamemode cummand
    aliases:
      - gm
      - gammode
      - givemecreativenerd
    usage: /<command> [survival | creative | adventure | spectator]
    permission: somtum.gamemode
  sethome:
    description: sethome command
    aliases:
      - sethouse
      - seth
      - savehome
    usage: /<command>
  home:
    description: home command
    aliases:
      - house
      - hom
      - mybed
    usage: /<command>
  delhome:
    description: delhome command
    aliases:
      - deletehome
      - deletehouse
      - byebyehome
    usage: /<command>
  togglejoinmusic:
    description: togglejoinmusic
    aliases:
      - tjm
      - togglemusic
      - togglejoin
    usage: /<command>
  stopsong:
    description: stop mucic
    aliases:
      - ihatemusic
      - stopmusic
      - musicstop
      - ms
    usage: /<command>
  playmusic:
    description: play mucic
    aliases:
      - pm
      - songplay
      - playsong
      - ps
      - sp
    usage: /<command>